//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmrdata
    {
        public int Id { get; set; }
        public Nullable<int> cdrRecordType { get; set; }
        public Nullable<int> globalCallID_callManagerId { get; set; }
        public Nullable<int> globalCallID_callId { get; set; }
        public Nullable<int> nodeId { get; set; }
        public string directoryNum { get; set; }
        public Nullable<int> callIdentifier { get; set; }
        public Nullable<int> dateTimeStamp { get; set; }
        public Nullable<int> numberPacketsSent { get; set; }
        public Nullable<int> numberOctetsSent { get; set; }
        public Nullable<int> numberPacketsReceived { get; set; }
        public Nullable<int> numberOctetsReceived { get; set; }
        public Nullable<int> numberPacketsLost { get; set; }
        public Nullable<int> jitter { get; set; }
        public Nullable<int> latency { get; set; }
        public string pkid { get; set; }
        public string directoryNumPartition { get; set; }
        public string globalCallId_ClusterID { get; set; }
        public string deviceName { get; set; }
        public string varVQMetrics { get; set; }
        public Nullable<int> duration { get; set; }
        public string videoContentType { get; set; }
        public Nullable<int> videoDuration { get; set; }
        public Nullable<int> numberVideoPacketsSent { get; set; }
        public Nullable<int> numberVideoOctetsSent { get; set; }
        public Nullable<int> numberVideoPacketsReceived { get; set; }
        public Nullable<int> numberVideoOctetsReceived { get; set; }
        public Nullable<int> numberVideoPacketsLost { get; set; }
        public Nullable<int> videoAverageJitter { get; set; }
        public Nullable<int> videoRoundTripTime { get; set; }
        public Nullable<int> videoOneWayDelay { get; set; }
        public string videoReceptionMetrics { get; set; }
        public string videoTransmissionMetrics { get; set; }
        public string videoContentType_channel2 { get; set; }
        public Nullable<int> videoDuration_channel2 { get; set; }
        public Nullable<int> numberVideoPacketsSent_channel2 { get; set; }
        public Nullable<int> numberVideoOctetsSent_channel2 { get; set; }
        public Nullable<int> numberVideoPacketsReceived_channel2 { get; set; }
        public Nullable<int> numberVideoOctetsReceived_channel2 { get; set; }
        public Nullable<int> numberVideoPacketsLost_channel2 { get; set; }
        public Nullable<int> videoAverageJitter_channel2 { get; set; }
        public Nullable<int> videoRoundTripTime_channel2 { get; set; }
        public Nullable<int> videoOneWayDelay_channel2 { get; set; }
        public string videoReceptionMetrics_channel2 { get; set; }
        public string videoTransmissionMetrics_channel2 { get; set; }
    }
}
