//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceRegistration
    {
        public int Id { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public Nullable<int> Type { get; set; }
        public string Description { get; set; }
        public Nullable<short> Reason { get; set; }
        public string Firmware { get; set; }
        public string DN { get; set; }
        public System.DateTime RegDateTime { get; set; }
    }
}
