//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinesMonitoring
    {
        public int Id { get; set; }
        public string VGIP { get; set; }
        public Nullable<int> DialPeer { get; set; }
        public Nullable<short> PortIndex { get; set; }
        public string NB { get; set; }
        public Nullable<bool> IsUp { get; set; }
        public short DisconnectionCause { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
