//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinesMonitoringPort
    {
        public int Id { get; set; }
        public int VGID { get; set; }
        public short PortIndex { get; set; }
        public string PortName { get; set; }
        public string LineNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
